import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import {useRouter} from "next/router";
import {useEffect, useState} from "react";
import {LogoutSuccessSnackbar} from "../components/logout/LogoutSuccessSnackbar";
import Box from "@mui/material/Box";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  const [logoutSnackbarOpen, setLogoutSnackbarOpen] = useState(false);
  useEffect(() => {
    if (router.query.logout) {
      setLogoutSnackbarOpen(true);
    }
  }, [router]);
  return (
    <>
      <Head>
        <title>Price Spy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <LogoutSuccessSnackbar open={logoutSnackbarOpen} onClose={()=>{
          setLogoutSnackbarOpen(false);
        }} />

        <Box>

        </Box>

      </main>
    </>
  )
}
