import Head from 'next/head'
import {Inter} from 'next/font/google'
import styles from '../styles/Home.module.css'
import {useRouter} from "next/router";
import {useEffect, useState} from "react";
import {LogoutSuccessSnackbar} from "../components/logout/LogoutSuccessSnackbar";
import Box from "@mui/material/Box";
import Card from "@mui/material/Card";
import Grid from "@mui/material/Grid";
import CardMedia from "@mui/material/CardMedia";
import CardContent from "@mui/material/CardContent";
import Typography from "@mui/material/Typography";
import Image from "next/image";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    const router = useRouter();
    const [logoutSnackbarOpen, setLogoutSnackbarOpen] = useState(false);
    useEffect(() => {
        if (router.query.logout) {
            setLogoutSnackbarOpen(true);
        }
    }, [router]);
    return (
        <>
            <Head>
                <title>Price Spy</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <LogoutSuccessSnackbar open={logoutSnackbarOpen} onClose={() => {
                    setLogoutSnackbarOpen(false);
                }}/>

                <Box>

                    <Card className={styles.mainCard}>
                        <Box className={styles.mainGrid}>
                            <Box className={styles.imageBox}>
                                <Image src={"/sales.svg"} alt={"sales"} height={500} width={500}/>
                            </Box>
                            <Box className={styles.mainContent}>
                                <Typography component={"div"} variant={"h3"} align={"center"}><p>Price Spy</p></Typography>
                                <Typography component={"div"} variant={"h4"} align={"center"}><p>Boost Your Profits and Skyrocket Your Sales!</p></Typography>

                                <p>Are you looking for a game-changing solution to enhance your business's profitability
                                    and drive more sales? Look no further than Price Spy, the ultimate tool to
                                    revolutionize
                                    your pricing strategy. With Price Spy, you can gain a competitive edge in the market
                                    and
                                    take your business to new heights.</p>

                                <p>Why choose Price Spy? It's simple. By harnessing the power of real-time price
                                    intelligence and market analysis, Price Spy empowers you to make informed pricing
                                    decisions that directly impact your bottom line. Here's how it works:</p>

                                <ol><li>Uncover Market Insights: Price Spy provides you with comprehensive market
                                    insights,
                                    allowing you to monitor your competitors' prices, promotions, and trends. Stay one
                                    step
                                    ahead by knowing exactly how your products are priced in the market and make
                                    data-driven
                                    decisions to optimize your pricing strategy.</li>

                                    <li>Maximize Profit Margins: With Price Spy, you can identify opportunities to
                                        maximize
                                        your profit margins. By analyzing market dynamics, demand fluctuations, and
                                        customer
                                        behavior, Price Spy helps you determine the optimal price points for your
                                        products,
                                        ensuring you achieve the perfect balance between profitability and
                                        competitiveness.</li>

                                    <li>Monitor Price Movements: Price Spy keeps a vigilant eye on price movements,
                                        alerting
                                        you to any changes in the market. Stay informed about price drops, promotions,
                                        or
                                        new
                                        entrants to the market, and adjust your pricing strategy accordingly. Never miss
                                        an
                                        opportunity to attract customers with competitive prices and drive more
                                        sales.</li>

                                    <li>Drive Customer Conversion: Price Spy enables you to offer competitive prices that
                                        resonate with your customers. By strategically adjusting your prices based on
                                        market
                                        dynamics and customer preferences, you can increase customer conversion rates,
                                        boost
                                        customer loyalty, and ultimately drive more sales.</li></ol>

                                <p>Ready to take your business to the next level? Embrace Price Spy and experience the
                                    power of data-driven pricing. Join the ranks of successful businesses who have
                                    harnessed
                                    the potential of Price Spy to improve their profits, increase sales, and outshine
                                    their
                                    competition. Don't miss out on this opportunity – start using Price Spy today and
                                    unlock
                                    your business's full potential!</p>

                                <p>Take action now and unlock the gateway to pricing success with Price Spy. Sign up
                                    today
                                    and witness the transformative impact on your business's profitability and sales
                                    growth.
                                    Don't wait – the time to maximize your profits is now!</p>
                            </Box>
                        </Box>
                    </Card>

                </Box>

            </main>
        </>
    )
}
